blank_issues_enabled: false
contact_links:
  - name: 🤔 Long question or ideas?
    url: https://github.com/deuscx/starter-vue-component/discussions
    about: Ask long-form questions and discuss ideas.
